config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :flight_classes
  resources :accommodations
  resources :trips
  resources :users

  get '/', to: "application#index"
  
  get '/flights', to: "flight_classes#index"
 
  post "/sessions/login", to: "sessions#create", as: 'new_login'

  get "/sessions/logout", to: "sessions#destroy", as: "log_out_session" 

  get "/sessions/cart", to: "sessions#show_cart", as: "cart"

  post "/sessions/add_flight", to: "sessions#add_flight"
  post "/sessions/add_accommodation", to: "sessions#add_accommodation"
  post "/sessions/add_destination", to: "sessions#add_destination"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
    has_many :trips
    has_many :users, through: :trips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :trips
    has_many :users, through: :trips

    def city_country
      "#{self.city}, #{self.country}"
    end

end

app/models/flight_class.rb
class FlightClass < ApplicationRecord
    has_many :trips
    has_many :users, through: :trips
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user
    belongs_to :destination
    belongs_to :flight_class
    belongs_to :accommodation

    def cost
      self.destination.cost.to_i + self.accommodation.cost.to_i + self.flight_class.cost.to_i 
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips
    has_many :destinations, through: :trips
    has_many :accommodations, through: :trips
    has_many :flight_classes, through: :trips

    validates :email, uniqueness: true

    has_secure_password

end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController

    def index
        @accommodations = Accommodation.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_user
    before_action :authenticate_user

    skip_before_action :authenticate_user, only: [:index]

    def index
        @user = User.new
    end

    def set_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def authenticate_user
        if @current_user
            #do nothing
        else 
          redirect_to '/'
        end 
    end
    
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

    skip_before_action :authenticate_user, only: [:index, :show]

    def index
        @destinations = Destination.all
    end

    def show
        @destination = Destination.find(params[:id])
    end


end

app/controllers/flight_classes_controller.rb
class FlightClassesController < ApplicationController

    def index
        @flights = FlightClass.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :authenticate_user, only: [:create]
    
    def create

        @user = User.find_by(email: params[:session][:email])

        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:err] = "Username or password is incorrect."
            redirect_to '/'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end

    def show_cart
      # if @current_user.id == params[:id]
        render :show_cart
      # else
      # end
    end

    def add_flight
      session[:flight_id] = params[:trip_params][:flight_id]
      # @flight = FlightClass.find(session[:flight_id])
      redirect_to cart_path
    end

    def add_accommodation
      session[:accommodation_id] = params[:trip_params][:accommodation_id]
      redirect_to cart_path
    end

    def add_destination
      session[:destination_id] = params[:trip_params][:destination_id]
      redirect_to cart_path
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def new
    @trip = Trip.new
    @users = User.all
    @destinations = Destination.all
    @accommodations = Accommodation.all
    @flights = FlightClass.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.create(trip_params)
    #byebug
    session[:destination_id] = nil
    session[:accommodation_id] = nil
    session[:flight_id] = nil
    redirect_to user_path(@trip.user)
  end

  def edit
    @trip = Trip.find(params[:id])
    @users = User.all
    @destinations = Destination.all
    @accommodations = Accommodation.all
    @flights = FlightClass.all
  end

  def update
    trip = Trip.find(params[:id])
    trip.update(trip_params)
    redirect_to trip_path(trip)
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to user_path(trip.user.id)
  end

  private

  def trip_params
    params.require(:trip).permit(:user_id, :destination_id, :flight_class_id, :accommodation_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user, only: [:new, :create, :show]

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    
    if @user.id == @current_user.id
      render :show
    else
      redirect_to user_path(@current_user)
    end
  end

  def new
    @user = User.find(params[:id])
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id

    if @user.valid?
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/"
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to "/"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/flight_classes_helper.rb
module FlightClassesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accommodations/index.html.erb
<main class="index">
    <h1>Accommodation Tier Options</h1>

    <div class="card-container">
        <% @accommodations.each do |acc| %>
            <div class="card">
                <img src=" <%= acc.img_url %> " alt=" <%= acc.name %> ">
                <h2>Tier: <%= acc.name %> </h2>
                <ul>
                    <li><strong>Cost:</strong> $<%= acc.cost %> </li>
                </ul>
                <p> <%= acc.description %> </p>

                <% if @current_user %>
                    <%= form_for :trip_params, url: "/sessions/add_accommodation" do |f| %>
                    <%= f.hidden_field :accommodation_id, value: acc.id %>
                    <%= f.submit "Add to Cart" %>
                    <% end %>
                <% end %>

            </div>
        <% end %>
    </div>
</main>

app/views/application/index.html.erb
<header class="landing">

  <div class="left">
  <div class="inner-container">
    <h1>Welcome to Tasty Tours</h1>
    <p>Give your tastebuds an adventure!</p>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <span><%= error %></span>
      <% end %>
    <% end %>

    <!-- Sign up form -->
    <%= form_for @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Your Name" %>

        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "Your Email" %>

        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "Password" %>

        <%= f.submit "Create an Account" %>

    <% end %>
  </div>
  </div>
  <div class="right">
  </div>
</header>
<main class="landing">
  <div class="content-container">
    <h3>Plan Your Trip</h3>
    <div class="info-container">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer porttitor tincidunt odio id laoreet. Maecenas quis libero ac magna porttitor vehicula. Aliquam viverra turpis et purus congue varius. Morbi suscipit imperdiet risus at elementum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer porttitor tincidunt odio id laoreet. Maecenas quis libero ac magna porttitor vehicula. Aliquam viverra turpis et purus congue varius. Morbi suscipit imperdiet risus at elementum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer porttitor tincidunt odio id laoreet. Maecenas quis libero ac magna porttitor vehicula. Aliquam viverra turpis et purus congue varius. Morbi suscipit imperdiet risus at elementum.</p>
    </div>
  </div>
  <div class="img-container">
    <img src="https://i.imgur.com/kT9LCtz.jpg" alt="A pasta dish you can learn to make in Italy">
    <img src="https://i.imgur.com/Te0tE42.jpg" alt="Learn to bake bread in France">
  </div>
</main>
<div id="signin-form" class="sign-in-container">
  <% if flash[:err] %>
      <span> <%= flash[:err] %> </span>
  <% end %>

  <!-- Sign in form -->
  <%= form_for :session, url: new_login_path do |f|  %>
      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "Email" %>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Password" %>

      <%= f.submit "Login" %>
  <% end %>
</div>

app/views/destinations/index.html.erb
<main class="index">
<div class="destination-card-container">
    <% @destinations.each do |destination| %>
        <div class="card">
            <img alt="<%= destination.city %>, <%= destination.country %>" src="<%= destination.img_url %>">
            <h2><%= destination.city %>, <%= destination.country %></h2>
            <div class="btn-container">
                <%= link_to 'View Destination', destination_path(destination) %>

                <% if @current_user %>
                    <%= form_for :trip_params, url: "/sessions/add_destination" do |f| %>
                    <%= f.hidden_field :destination_id, value: destination.id %>
                    <%= f.submit "Add to Cart" %>
                    <% end %>
                <% end %>
            </div>

        </div>
        
    <% end %>
    </div>
</main>

app/views/destinations/show.html.erb
<main class="show" style="background: linear-gradient(rgba(0,0,0,.25), rgba(0,0,0,.25)), url( <%= @destination.bg_img_url %> );" >
    <div class="container">
        <div class="tagline">Eat and learn to make <%= @destination.cuisine %> in...</div>
        <h1> <%= @destination.city %>, <%= @destination.country %> </h1>
        <div id="ImageGallery">
            <div class="row">
                <figure>
                    <img src="<%= @destination.img_url2 %>" alt="Typical cuisine found in <%= @destination.city %>, <%= @destination.country %>" >
                    <figcaption>Food in <%= @destination.city %>, <%= @destination.country %></figcaption>
                </figure>
                <figure>
                    <img src="<%= @destination.img_url %>" alt="Typical cuisine found in <%= @destination.city %>, <%= @destination.country %>" >
                    <figcaption>Food in <%= @destination.city %>, <%= @destination.country %></figcaption>
                </figure>
                <figure>
                    <img src="<%= @destination.img_url3 %>" alt="Typical cuisine found in <%= @destination.city %>, <%= @destination.country %>" >
                    <figcaption>Food in <%= @destination.city %>, <%= @destination.country %></figcaption>
                </figure>
            </div>
        </div>
        <h3> <%= @destination.cuisine %> </h3>
        <p> <%= @destination.description %> </p>

        <% if @current_user %>
            <%= form_for :trip_params, url: "/sessions/add_destination" do |f| %>
            <%= f.hidden_field :destination_id, value: @destination.id %>
            <%= f.submit "Add to Cart" %>
            <% end %>
        <% end %>

    </div>
</main>

app/views/flight_classes/index.html.erb
<main class="index">
    <h1>Flight Tier Options</h1>

    <div class="card-container">
        <% @flights.each do |flight| %>
            <div class="card">
                <img src=" <%= flight.img_url %> " alt=" <%= flight.name %> ">
                <h2>Flight Tier: <%= flight.name %> </h2>
                <ul>
                    <li><strong>Cost:</strong> $<%= flight.cost %> </li>
                </ul>
                <p> <%= flight.description %> </p>
                
                <% if @current_user %>
                    <%= form_for :trip_params, url: "/sessions/add_flight" do |f| %>
                    <%= f.hidden_field :flight_id, value: flight.id %>
                    <%= f.submit "Add to Cart" %>
                    <% end %>
                <% end %>

            </div>
        <% end %>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasty Travel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/05cb685f53.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Arvo|Lato" rel="stylesheet">
  </head>
  <nav>
    <div class="inner-nav">
      <span>Tasty Tours</span>
      <a class="logo" href="/"><i class="fad fa-plane"></i></a>
      <% if @current_user %>
      <span>Welcome <%= @current_user.name %>!</span>
        <a class="hover-state" href="<%= new_trip_path %>">Create a Trip</a>
      <% end %>
      <% if @current_user %>
        <a class="hover-state" href="<%= user_path(@current_user) %>">Profile</a>
      <% end %>
      <a class="hover-state" href="<%= destinations_path %>">Destinations</a>
      <% if @current_user %>
      <a class="hover-state" href="<%= flight_classes_path %>">Flights</a>
      <a class="hover-state" href="<%= accommodations_path %>">Accommodations</a>
      <a class="hover-state" href="<%= cart_path %>">Cart</a>
          <a class="hover-state" href="<%= log_out_session_path %>">Log Out</a>
        <% else %>
          <a class="hover-state" href="/#signin-form">Login</a>
        <% end %>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>

  <%= f.hidden_field :user_id, :value => @current_user.id %>

  <%= f.label :destination_id %>
  <%= f.collection_select :destination_id, @destinations, :id, :city_country %>
  <%= f.label :flight_class_id %>
  <%= f.collection_select :flight_class_id, @flights, :id, :name %>
  <%= f.label :accommodation_id %>
  <%= f.collection_select :accommodation_id, @accommodations, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<main class="new-edit">
    <h1>Edit Your Trip!</h1>
    <%= render 'form' %>
</main>

app/views/trips/new.html.erb
<main class="new-edit">
    <h1>Create a new Trip!</h1>
    <%= render 'form' %>
</main>

app/views/trips/show.html.erb
<main class="trip-show">
  <div class="container">
    <h1><%= @trip.destination.city_country %></h1>
    <h2>Total Trip Cost: $<%= @trip.cost %></h2>
    <div class="card-container">
      <div class="card">
        <img src="<%= @trip.destination.img_url %>" alt="<%= @trip.destination.cuisine %>">
        <h3>Learn to make: <%= @trip.destination.cuisine %></h3>
        <p>$<%= @trip.destination.cost %></p>
      </div>
      <div class="card">
        <img src="<%= @trip.accommodation.img_url %>" alt="<%= @trip.accommodation.name %>">
        <h3>Accomodation Tier: <%= @trip.accommodation.name %></h3>
        <p>$<%= @trip.accommodation.cost %></p>
      </div>
      <div class="card">
        <img src="<%= @trip.flight_class.img_url %>" alt="<%= @trip.flight_class.name %>">
        <h3>Flight Class: <%= @trip.flight_class.name %></h3>
        <p>$<%= @trip.flight_class.cost %></p>
      </div>
    </div>
    <%= link_to "Edit Trip Details", edit_trip_path(@trip) %>

    <%= button_to "Delete Trip", trip_path(@trip), method: :delete %>
  </div>
</main>

app/views/users/index.html.erb
<h1>User Index</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<main class="user-show">
  <h1>Hello <%= @user.name %>!</h1>

  <%= link_to 'Create a Trip', new_trip_path %>

  <h2>Your Trips:</h2>

<div class="card-container">
  <% if @user.trips.length == 0 %>
    <p style="margin: 3rem 0; text-align: center; font-size: 1.15rem; color: #2f2f2f;">You have no scheduled trips at this time.</p>
  <% else %>
    <% @user.trips.each do |trip| %>
      <div class="card">
        <img src="<%= trip.destination.img_url %>" alt="<%= trip.destination.city %>, <%= trip.destination.country %>">

        <h3><%= trip.destination.city %>, <%= trip.destination.country %></h3>
        <%= link_to "Trip Details", trip_path(trip) %>
      </div>
    <% end %>
  <% end %>
  </div>
  
  <%= button_to "Delete Account", user_path(@user), method: :delete %>
</main>